### ISSUE TITLE
Can't create pagination object with interaction (possibly outdated types?)

### ISSUE THREAD

**Issue by obfuscatedgenerated** [imranbarbhuiya/pagination.djs#177]
### Issue description

Typescript will not allow me to pass my interaction (specifically a ChatInputCommandInteraction as narrowed) to the constructor.

```
Argument of type 'ChatInputCommandInteraction<CacheType>' is not assignable to parameter of type 'ChatInputCommandInteraction<"cached"> | MessageContextMenuCommandInteraction<"cached"> | UserContextMenuCommandInteraction<"cached"> | AnySelectMenuInteraction<...> | ButtonInteraction<...> | ModalSubmitInteraction<...> | Message<...>'.
  Type 'ChatInputCommandInteraction<CacheType>' is not assignable to type 'ChatInputCommandInteraction<"cached">'.
    Type 'CacheType' is not assignable to type '"cached"'.
      Type '"raw"' is not assignable to type '"cached"'.
```

If I simply add ts-expect-error to ignore Typescript, the module functions just fine.

### Code sample

```TypeScript
client.on("interactionCreate", async (interaction: Interaction) => {
    if (!interaction.isCommand()) {
        return;
    }

    interaction = interaction as ChatInputCommandInteraction;

    // in my code, it is passed to the appropriate command function, but let's just call pagination here

    // this will not build!
    const pagination = new Pagination(interaction);
}
```

### Package version

4.0.10

### Node.js version

18.15.0 [TS: 5.1.6]

**Comment by imranbarbhuiya** [comment]
It's due to djs version mismatch. You've 2 versions of djs installed. Depending on the package manager u using, you'll need to run `dedupe` command. If the package manager don't have any dedupe command then Uninstall and reinstalling djs should fix it

**Comment by im-calvin** [comment]
I'm running into the same issue here with only 1 version of djs. I am using ESM6 syntax from import: `import {Pagination} from 'pagination.djs'`

Telling ts to ignore it via `@ts-ignore` works as mentioned above

**Comment by imranbarbhuiya** [comment]
What package manager u using?

**Comment by im-calvin** [comment]
I'm using `npm v9.6.5, node v18.12.1`

**Comment by im-calvin** [comment]
I've tried it and it doesn't fix the problem
![image](https://github.com/imranbarbhuiya/pagination.djs/assets/61614687/b6c2d71e-efb2-4670-aef5-340e31db8ec7)

**Comment by imranbarbhuiya** [comment]
I didnt read the first ss code properly and your issue is the same too, so u r passing `interaction` with `CacheType` `raw | cached` but this package takes only the `cached` type as it won't work with `raw` type. I published another release to remove the `cached` generic from code to avoid confusion and its safe to remove too as interactions mostly come from cached guilds only. Update to `pagination.djs@4.0.12` and it should fix it

**Comment by im-calvin** [comment]
Perfect! Thanks it works now!

**Comment by imranbarbhuiya** [comment]
> Did you mean to say that you removed the raw type from the code? My understanding is that the issue was that I had a possibility of CacheType raw

I removed the strict type of `cached` to allow passing both `cached` and `raw` types
